
export const countries = [
    { "value": "Afghanistan", "label": "Afghanistan" },
    { "value": "Albania", "label": "Albania" },
    { "value": "Algeria", "label": "Algeria" },
    { "value": "American-Samoa", "label": "American Samoa" },
    { "value": "Andorra", "label": "Andorra" },
    { "value": "Angola", "label": "Angola" },
    { "value": "Anguilla", "label": "Anguilla" },
    { "value": "Antarctica", "label": "Antarctica" },
    { "value": "Antigua", "label": "Antigua And Barbuda" },
    { "value": "Argentina", "label": "Argentina" },
    { "value": "Armenia", "label": "Armenia" },
    { "value": "Aruba", "label": "Aruba" },
    { "value": "Australia", "label": "Australia" },
    { "value": "Austria", "label": "Austria" },
    { "value": "Azerbaija", "label": "Azerbaijan" },
    { "value": "Bahamas", "label": "Bahamas" },
    { "value": "Bahrain", "label": "Bahrain" },
    { "value": "Bangladesh", "label": "Bangladesh" },
    { "value": "Barbados", "label": "Barbados" },
    { "value": "Belarus", "label": "Belarus" },
    { "value": "Belgium", "label": "Belgium" },
    { "value": "Belize", "label": "Belize" },
    { "value": "Beni", "label": "Benin" },
    { "value": "Bermuda", "label": "Bermuda" },
    { "value": "Bhuta", "label": "Bhutan" },
    { "value": "Bolivia", "label": "Bolivia" },
    { "value": "Bosnia", "label": "Bosnia And Herzegovina" },
    { "value": "Botswana", "label": "Botswana" },
    { "value": "Bouvet-Island", "label": "Bouvet Island" },
    { "value": "Brazil", "label": "Brazil" },
    { "value": "Brunei-Darussalam", "label": "Brunei Darussalam" },
    { "value": "Bulgaria", "label": "Bulgaria" },
    { "value": "Burkina-Faso", "label": "Burkina Faso" },
    { "value": "Burundi", "label": "Burundi" },
    { "value": "Cambodia", "label": "Cambodia" },
    { "value": "Cameroo", "label": "Cameroon" },
    { "value": "Canada", "label": "Canada" },
    { "value": "Cape-Verde", "label": "Cape Verde" },
    { "value": "Cayman-Islands", "label": "Cayman Islands" },
    { "value": "Central-African-Republic", "label": "Central African Republic" },
    { "value": "Chad", "label": "Chad" },
    { "value": "Chile", "label": "Chile" },
    { "value": "China", "label": "China" },
    { "value": "Christmas-Island", "label": "Christmas Island" },
    { "value": "Colombia", "label": "Colombia" },
    { "value": "Comoros", "label": "Comoros" },
    { "value": "Congo", "label": "Congo" },
    { "value": "Cook-Islands", "label": "Cook Islands" },
    { "value": "Costa-Rica", "label": "Costa Rica" },
    { "value": "Croatia", "label": "Croatia" },
    { "value": "Cuba", "label": "Cuba" },
    { "value": "Cyprus", "label": "Cyprus" },
    { "value": "Czech-Republic", "label": "Czech Republic" },
    { "value": "Denmark", "label": "Denmark" },
    { "value": "Djibouti", "label": "Djibouti" },
    { "value": "Dominica", "label": "Dominica" },
    { "value": "Dominican-Republic", "label": "Dominican Republic" },
    { "value": "East-Timor", "label": "East Timor" },
    { "value": "Ecuador", "label": "Ecuador" },
    { "value": "Egypt", "label": "Egypt" },
    { "value": "El-Salvador", "label": "El Salvador" },
    { "value": "Equatorial-Guinea", "label": "Equatorial Guinea" },
    { "value": "Eritrea", "label": "Eritrea" },
    { "value": "Estonia", "label": "Estonia" },
    { "value": "Ethiopia", "label": "Ethiopia" },
    { "value": "Falkland-Islands-malvinas", "label": "Falkland Islands (malvinas)" },
    { "value": "Faroe-Islands", "label": "Faroe Islands" },
    { "value": "Fiji", "label": "Fiji" },
    { "value": "Finland", "label": "Finland" },
    { "value": "France", "label": "France" },
    { "value": "French-Guiana", "label": "French Guiana" },
    { "value": "French-Polynesia", "label": "French Polynesia" },
    { "value": "French-Southern-Territories", "label": "French Southern Territories" },
    { "value": "Gabo", "label": "Gabon" },
    { "value": "Gambia", "label": "Gambia" },
    { "value": "Georgia", "label": "Georgia" },
    { "value": "Germany", "label": "Germany" },
    { "value": "Ghana", "label": "Ghana" },
    { "value": "Gibraltar", "label": "Gibraltar" },
    { "value": "Greece", "label": "Greece" },
    { "value": "Greenland", "label": "Greenland" },
    { "value": "Grenada", "label": "Grenada" },
    { "value": "Guadeloupe", "label": "Guadeloupe" },
    { "value": "Guam", "label": "Guam" },
    { "value": "Guatemala", "label": "Guatemala" },
    { "value": "Guinea", "label": "Guinea" },
    { "value": "Guinea-bissau", "label": "Guinea-bissau" },
    { "value": "Guyana", "label": "Guyana" },
    { "value": "Haiti", "label": "Haiti" },
    { "value": "Honduras", "label": "Honduras" },
    { "value": "Hong-Kong", "label": "Hong Kong" },
    { "value": "Hungary", "label": "Hungary" },
    { "value": "Iceland", "label": "Iceland" },
    { "value": "India", "label": "India" },
    { "value": "Indonesia", "label": "Indonesia" },
    {
        "value": "Iran", "label": "Iran"
    },
    { "value": "Iraq", "label": "Iraq" },
    { "value": "Ireland", "label": "Ireland" },
    { "value": "Israel", "label": "Israel" },
    { "value": "Italy", "label": "Italy" },
    { "value": "Jamaica", "label": "Jamaica" },
    { "value": "Japa", "label": "Japan" },
    { "value": "Jorda", "label": "Jordan" },
    { "value": "Kazaksta", "label": "Kazakstan" },
    { "value": "Kenya", "label": "Kenya" },
    { "value": "Kiribati", "label": "Kiribati" },
    { "value": "Korea", "label": "Korea" },
    { "value": "Kosovo", "label": "Kosovo" },
    { "value": "Kuwait", "label": "Kuwait" },
    { "value": "Kyrgyzsta", "label": "Kyrgyzstan" },

    { "value": "Latvia", "label": "Latvia" },
    { "value": "Lebano", "label": "Lebanon" },
    { "value": "Lesotho", "label": "Lesotho" },
    { "value": "Liberia", "label": "Liberia" },
    { "value": "Liechtenstei", "label": "Liechtenstein" },
    { "value": "Lithuania", "label": "Lithuania" },
    { "value": "Luxembourg", "label": "Luxembourg" },

    { "value": "Madagascar", "label": "Madagascar" },
    { "value": "Malawi", "label": "Malawi" },
    { "value": "Malaysia", "label": "Malaysia" },
    { "value": "Maldives", "label": "Maldives" },
    { "value": "Mali", "label": "Mali" },
    { "value": "Malta", "label": "Malta" },
    { "value": "Martinique", "label": "Martinique" },
    { "value": "Mauritania", "label": "Mauritania" },
    { "value": "Mauritius", "label": "Mauritius" },
    { "value": "Mayotte", "label": "Mayotte" },
    { "value": "Mexico", "label": "Mexico" },
    { "value": "Monaco", "label": "Monaco" },
    { "value": "Mongolia", "label": "Mongolia" },
    { "value": "Montserrat", "label": "Montserrat" },
    { "value": "Montenegro", "label": "Montenegro" },
    { "value": "Morocco", "label": "Morocco" },
    { "value": "Mozambique", "label": "Mozambique" },
    { "value": "Myanmar", "label": "Myanmar" },
    { "value": "Namibia", "label": "Namibia" },
    { "value": "Nepal", "label": "Nepal" },
    { "value": "Netherlands", "label": "Netherlands" },
    { "value": "Netherlands-Antilles", "label": "Netherlands Antilles" },
    { "value": "New-Caledonia", "label": "New Caledonia" },
    { "value": "New-Zealand", "label": "New Zealand" },
    { "value": "Nicaragua", "label": "Nicaragua" },
    { "value": "Niger", "label": "Niger" },
    { "value": "Nigeria", "label": "Nigeria" },
    { "value": "Niue", "label": "Niue" },
    { "value": "Norfolk-Island", "label": "Norfolk Island" },
    { "value": "Norway", "label": "Norway" },
    { "value": "Oma", "label": "Oman" },
    { "value": "Pakista", "label": "Pakistan" },
    { "value": "Palau", "label": "Palau" },
    { "value": "Panama", "label": "Panama" },
    { "value": "Papua-New-Guinea", "label": "Papua New Guinea" },
    { "value": "Paraguay", "label": "Paraguay" },
    { "value": "Peru", "label": "Peru" },
    { "value": "Philippines", "label": "Philippines" },
    { "value": "Pitcair", "label": "Pitcairn" },
    { "value": "Poland", "label": "Poland" },
    { "value": "Portugal", "label": "Portugal" },
    { "value": "Puerto-Rico", "label": "Puerto Rico" },
    { "value": "Qatar", "label": "Qatar" },
    { "value": "Reunio", "label": "Reunion" },
    { "value": "Romania", "label": "Romania" },
    { "value": "Russian", "label": "Russian Federation" },
    { "value": "Rwanda", "label": "Rwanda" },
    { "value": "Saint-Lucia", "label": "Saint Lucia" },
    { "value": "Samoa", "label": "Samoa" },
    { "value": "San-Marino", "label": "San Marino" },
    { "value": "Saudi-Arabia", "label": "Saudi Arabia" },
    { "value": "Senegal", "label": "Senegal" },
    { "value": "Serbia", "label": "Serbia" },
    { "value": "Seychelles", "label": "Seychelles" },
    { "value": "Sierra-Leone", "label": "Sierra Leone" },
    { "value": "Singapore", "label": "Singapore" },
    { "value": "Slovakia", "label": "Slovakia" },
    { "value": "Slovenia", "label": "Slovenia" },
    { "value": "Solomon-Islands", "label": "Solomon Islands" },
    { "value": "Somalia", "label": "Somalia" },
    { "value": "South-Africa", "label": "South Africa" },
    { "value": "Spain", "label": "Spain" },
    { "value": "Sri-Lanka", "label": "Sri Lanka" },
    { "value": "Suda", "label": "Sudan" },
    { "value": "Suriname", "label": "Suriname" },
    { "value": "Swaziland", "label": "Swaziland" },
    { "value": "Swede", "label": "Sweden" },
    { "value": "Switzerland", "label": "Switzerland" },
    { "value": "Tajikista", "label": "Tajikistan" },
    { "value": "Thailand", "label": "Thailand" },
    { "value": "Togo", "label": "Togo" },
    { "value": "Tokelau", "label": "Tokelau" },
    { "value": "Tonga", "label": "Tonga" },
    { "value": "Trinidad-And-Tobago", "label": "Trinidad And Tobago" },
    { "value": "Tunisia", "label": "Tunisia" },
    { "value": "Turkey", "label": "Turkey" },
    { "value": "Turkmenista", "label": "Turkmenistan" },
    { "value": "TurksAndCaicosIslands", "label": "Turks And Caicos Islands" },
    { "value": "Tuvalu", "label": "Tuvalu" },
    { "value": "Uganda", "label": "Uganda" },
    { "value": "Ukraine", "label": "Ukraine" },
    { "value": "UnitedArabEmirates", "label": "United Arab Emirates" },
    { "value": "United-Kingdom", "label": "United Kingdom" },
    { "value": "United-states", "label": "United States" },
    { "value": "Uruguay", "label": "Uruguay" },
    { "value": "Uzbekista", "label": "Uzbekistan" },
    { "value": "Vanuatu", "label": "Vanuatu" },
    { "value": "Venezuela", "label": "Venezuela" },
    { "value": "Viet-Nam", "label": "Viet Nam" },
    {
        "value": "Virgin-Islands", "label": "Virgin Islands"
    },
    { "value": "Yeme", "label": "Yemen" },
    { "value": "Zambia", "label": "Zambia" },
    { "value": "Zimbabwe", "label": "Zimbabwe" },

]

export default countries